wevm/viem

.changeset/silly-crews-confess.md, src/types/log.ts
=> fix: type error

src/utils/abi/decodeAbiParameters.test.ts, src/utils/abi/decodeAbiParameters.ts, src/utils/abi/decodeEventLog.test.ts
=> fix: decode empty string parts

site/docs/ethers-migration.md, site/docs/getting-started.md, site/docs/introduction.md
=> Fix: typos

.github/workflows/main.yml, package.json, src/_test/globalSetup.ts, src/actions/public/readContract.test-d.ts, src/types/contract.test-d.ts
Adds type tests to a few key places.
=> feat: test types

.changeset/clean-dryers-jump.md, src/actions/public/multicall.test.ts, src/actions/public/multicall.ts
=> fix: return type for `allowFailure: false` on `multicall`

.changeset/funny-bees-collect.md, src/actions/wallet/signTypedData.test-d.ts, src/actions/wallet/signTypedData.ts, src/clients/decorators/wallet.ts
Fixes typed data inference and adds a few type tests.
<details><summary>Details</summary>
<p>
</p>
</details>
=> fix: typed data inference

site/docs/actions/wallet/addChain.md
https://github.com/wagmi-dev/viem/issues/266
=> docs: add chain parametr

.changeset/dull-jeans-rest.md, src/accounts/index.test.ts, src/accounts/index.ts
=> chore: export account utils

.changeset/big-jobs-jam.md, src/accounts/wordlists/czech.ts, src/accounts/wordlists/english.ts, src/accounts/wordlists/french.ts, src/accounts/wordlists/italian.ts, src/accounts/wordlists/japanese.ts, src/accounts/wordlists/korean.ts, src/accounts/wordlists/simplifiedChinese.ts, src/accounts/wordlists/spanish.ts, src/accounts/wordlists/traditionalChinese.ts
=> fix: wordlist exports

site/docs/actions/wallet/sendTransaction.md
=> chore: fix const name in docs

.changeset/wicked-dolls-shake.md, src/clients/createWalletClient.ts
=> fix: forward options to transport when creating wallet client

.changeset/config.json, .vscode/extensions.json, examples/blocks/watching-blocks/index.ts, examples/contracts/multicall/index.ts, examples/transactions/fetching-transactions/index.ts, package.json, playgrounds/browser/src/App.tsx, playgrounds/browser/src/index.tsx, site/tailwind.config.js
Otherwise rome keeps acting up when editing those files manually as the IDE doesn't care what the package.json script points at.
=> chore: apply rome on full package

src/accounts/hdKeyToAccount.test.ts, src/adapters/ethers.test.ts, src/types/eip1193.ts
=> test: chore

src/actions/getContract.bench.ts, src/errors/abi.ts, src/errors/account.ts, src/errors/address.ts, src/errors/base.ts, src/errors/block.ts, src/errors/chain.ts, src/errors/contract.ts, src/errors/data.ts, src/errors/encoding.ts, src/errors/ens.ts, src/errors/estimateGas.ts, src/errors/log.ts, src/errors/node.ts, src/errors/request.ts, src/errors/rpc.ts, src/errors/transaction.ts, tsconfig.base.json
I left a few `TODO` comments in there, please check those out. Not sure about those :)
... I'm checking the other tsconfig rules that I left `TODOs` for in the `TS5` upgrade PR.
=> chore: enable noImplicitOverride, noUnusedLocals and noUnusedParameters

.github/CONTRIBUTING.md, .github/workflows/bench.yml, .github/workflows/on-pull-request.yml, .github/workflows/verify.yml, src/_test/constants.ts, src/_test/globalSetup.ts, src/_test/index.ts, src/_test/setup.ts, src/_test/utils.ts, src/actions/public/call.test.ts, src/actions/public/createContractEventFilter.test.ts, src/actions/public/createEventFilter.test.ts, src/actions/public/estimateGas.test.ts, src/actions/public/getBlock.test.ts, src/actions/public/getBlockTransactionCount.test.ts, src/actions/public/getBytecode.test.ts, src/actions/public/getFeeHistory.test.ts, src/actions/public/getFilterChanges.test.ts, src/actions/public/getFilterLogs.test.ts, src/actions/public/getLogs.test.ts, src/actions/public/getStorageAt.test.ts, src/actions/public/getTransaction.test.ts, src/actions/public/multicall.test.ts, src/actions/public/readContract.test.ts, src/actions/test/reset.test.ts, src/actions/test/setRpcUrl.test.ts, src/clients/decorators/public.test.ts, src/clients/decorators/test.test.ts, src/errors/request.test.ts, src/utils/rpc.test.ts
Setting defaults for test constants so PR forks can run tests.
=> test: default constants

src/utils/abi/encodeAbiParameters.bench.ts, src/utils/abi/encodeAbiParameters.ts
=> chore: revert #971

.github/actions/setup-wagmi/action.yml, .github/workflows/verify.yml
Adds Wagmi typechecking and build to CI
=> ci: add wagmi typechecking

.changeset/chilly-poems-attack.md, src/chains/definitions/xrOne.ts, src/chains/index.ts
This PR adds a new XR One chain to the project.
Detailed summary
Added xrOne chain definition to chains/index.ts
Created xrOne chain definition in chains/definitions/xrSepolia.ts with ID 273
Configured xrOne with native currency, RPC URLs, block explorers, and set as a mainnet
=> Add XR One chain (#2)

.changeset/clean-papayas-speak.md, src/chains/definitions/sonic.ts
Adding multicall3 to sonic config
=> sonic multicall3

.changeset/pink-ravens-hope.md, site/pages/op-stack/chains.md, src/chains/definitions/zircuit.ts, src/chains/definitions/zircuitTestnet.ts
adding contract addresses to the already existing chain configs
=> Add Zircuit and Zircuit Testnet Contract Addresses 😺

.changeset/fresh-needles-design.md, src/zksync/actions/deployContract.test.ts, src/zksync/actions/deployContract.ts, src/zksync/constants/address.ts
Provide contract and account deployment using `create2` method.
=> fix(zksync): enable contract and account deployment using `create2`

.changeset/light-walls-unite.md, src/chains/definitions/abstractTestnet.ts
- Update to use etherscan instead of old explorer
- This is an official partnership
- https://x.com/0xcygaar/status/1876312502977667523?s=46
=> chore: update abstract block explorer to use etherscan

.changeset/grumpy-insects-tie.md, src/chains/definitions/kroma.ts, src/chains/definitions/kromaSepolia.ts
=> feat: add Multicall address to Kroma

src/actions/public/getContractEvents.ts
It is solving the wrong documentation in the `getContractEvents.ts` file, where it points to a different  URL
it is associated with https://github.com/wevm/viem/issues/3217
---
=> Updated doc string link for `getContractEvents` function

site/pages/docs/actions/wallet/addChain.md
=> docs(addChain): correct RPC namespace

.changeset/sweet-cows-begin.md, src/chains/definitions/bitlayer.ts, src/chains/definitions/bitlayerTestnet.ts
Add bitlayer mainnet & testnet `Multicall3` address, refer to https://docs.bitlayer.org/docs/Build/DeveloperResources/Contracts/
=> Add bitlayer mainnet & testnet `Multicall3` address

.changeset/two-crabs-push.md, src/errors/contract.test.ts, src/errors/contract.ts
=> Add raw revert data to ContractFunctionRevertedError

.changeset/plenty-rules-press.md, src/chains/definitions/bitlayer.ts
Add Multicall V3 contract for Bitlayer.
=> feat: add MulticallV3 for Bitlayer

.changeset/unlucky-pears-cry.md, src/chains/definitions/premiumBlock.ts, src/chains/index.ts
Reopened [#3260](https://github.com/wevm/viem/pull/3260)
=> Add premium block

src/chains/definitions/abstract.ts
=> chore: adjust config

.changeset/great-dancers-wonder.md, src/chains/definitions/cronoszkEVM.ts
Added `multicall3` contract to Cronos zkEVM chain
=> feat: add multicall3 address for cronoszkEVM

.changeset/eighty-dots-exist.md, src/chains/definitions/forta.ts, src/chains/index.ts
=> feat: add forta chain

.changeset/lazy-kings-work.md, src/chains/definitions/songbird.ts
=> feat: add Multicall address to Songbird

.changeset/clean-oranges-smash.md, src/chains/definitions/lightlinkPegasus.ts, src/chains/definitions/lightlinkPhoenix.ts
Add multicall3 contract info for LightLink Phoenix and Pegasus chain definitions.
=> Add multicall3 to LightLink chain definitions

.changeset/strange-buckets-exist.md, src/chains/definitions/xrOne.ts
=> Correct XR1 chain details.

.changeset/little-starfishes-trade.md, src/chains/definitions/botanixTestnet.ts
ref: https://docs.botanixlabs.xyz/botanix-labs/how-to-use-the-botanix-evm/getting-started-with-the-botanix-evm-testnet#chain-details
=> chore: updated Botanix testnet details

.changeset/thick-rivers-promise.md, src/chains/definitions/worldchainSepolia.ts
This PR does:
- Add WorldScan apiUrl
- Remove redundant rpc
=> fix: worldchain sepolia chain

.changeset/breezy-chairs-hear.md, src/chains/definitions/b3.ts, src/chains/definitions/b3Sepolia.ts
=> chore: add B3 multicall3

src/chains/definitions/story.ts
=> Add block explorer for Story chain

.changeset/heavy-hats-explode.md, src/chains/definitions/polynomial.ts, src/chains/definitions/polynomialSepolia.ts, src/chains/index.ts
=> feat: add Polynomial network

.changeset/twenty-moons-smash.md, src/chains/definitions/xdc.ts
=> Change XDC Name

.changeset/violet-cars-thank.md, src/chains/definitions/fluentTestnet.ts, src/chains/index.ts
=> feat: add Fluent network

.changeset/lovely-pears-fix.md, src/chains/definitions/real.ts
Updated default RPC node for real chain. We moved from dRPC support.
=> Update real chain

.changeset/saga-vanity-urls.md, src/chains/definitions/saga.ts
We are using a load balanced vanity url for explorer and RPC. This PR upgrades the old one.
=> Use saga vanity urls

.changeset/serious-pots-sort.md, src/actions/public/simulateBlocks.ts
fix: returnData can't be decoded https://github.com/wevm/viem/discussions/3444
As some data cannot be decoded using decodeFunctionResult, I think we need this fix.
=> fix: returnData can't be decoded

.changeset/slimy-books-film.md, site/pages/zksync/actions/isWithdrawalFinalized.md, site/sidebar.ts, src/zksync/actions/isWithdrawalFinalized.test.ts, src/zksync/actions/isWithdrawalFinalized.ts, src/zksync/decorators/publicL1.test.ts, src/zksync/decorators/publicL1.ts, src/zksync/index.ts
Add helper action `isWithdrawalFinalized` which provides easy way to check weather a withdraw transaction is finalized on L1.
=> feat(zksync): add `isWithdrawalFinalized` action

.changeset/tasty-pillows-impress.md, src/chains/definitions/somniaTestnet.ts, src/chains/index.ts
=> Add Somnia Testnet

.changeset/violet-bikes-hear.md, src/chains/definitions/inkSepolia.ts
- feat: add Multicall3 address to Ink Sepolia
=> Feat: add Multicall3 address to Ink Sepolia

.changeset/real-chicken-sleep.md, site/pages/zksync/actions/deposit.md, site/sidebar.ts, src/zksync/actions/deposit.test.ts, src/zksync/actions/deposit.ts, src/zksync/constants/address.ts, src/zksync/decorators/walletL1.test.ts, src/zksync/decorators/walletL1.ts, src/zksync/index.ts, src/zksync/utils/bridge/applyL1ToL2Alias.test.ts, src/zksync/utils/bridge/applyL1ToL2Alias.ts, src/zksync/utils/bridge/undoL1ToL2Alias.test.ts, src/zksync/utils/bridge/undoL1ToL2Alias.ts
Added `deposit` action in order to provide depositing funds from L1 to L2 chain. Also, util functions for mapping contract address between L1 and L2 are also provided.
=> feat(zksync): add `deposit` action, apply and undo alias util functions

.changeset/perfect-lemons-deny.md, src/experimental/index.ts
=> chore: add exports

.changeset/bright-buttons-flash.md, src/chains/definitions/megaethTestnet.ts
Add MegaETH Testnet multicall3 contract address
https://www.megaexplorer.xyz/address/0xcA11bde05977b3631167028862bE2a173976CA11
=> feat: add megaeth testnet multicall3 address

.changeset/witty-wombats-taste.md, src/op-stack/actions/estimateContractL1Fee.test.ts, src/op-stack/actions/estimateContractL1Gas.test.ts, src/op-stack/actions/estimateL1Fee.test.ts, src/op-stack/actions/estimateL1Fee.ts, src/op-stack/actions/estimateL1Gas.test.ts, src/op-stack/actions/estimateL1Gas.ts, src/op-stack/actions/estimateTotalGas.test.ts
=> fix: resolves #3513

.changeset/rich-cougars-laugh.md, pnpm-lock.yaml, src/actions/ens/getEnsAddress.test.ts, src/actions/ens/getEnsAddress.ts, src/actions/ens/getEnsResolver.test.ts, src/actions/ens/getEnsResolver.ts, src/actions/ens/getEnsText.test.ts, src/actions/ens/getEnsText.ts, src/chains/definitions/berachain.ts, src/chains/definitions/berachainTestnetbArtio.ts, src/chains/definitions/linea.ts, src/chains/definitions/lineaSepolia.ts, src/chains/definitions/story.ts, src/chains/definitions/storyAeneid.ts, src/types/chain.ts
Resolves unintended behavior that could arise from chain-specific ENS resolvers.
=> feat: `ensTlds` chain config

src/types/block.ts
genesis is technically an accepted block tag, yet not sure its practical usage
=> doc(types): remarks for block tag and its usage

.changeset/stupid-weeks-complain.md, src/chains/definitions/worldchainSepolia.ts
Please see: https://docs.world.org/world-chain/developers/world-chain-contracts
This PR fixes the incorrect disputeGameFactory that is listed for World Sepolia
=> Fix disputegameFactory for World Sepolia

.changeset/beige-onions-watch.md, site/pages/docs/contract/multicall.md, src/actions/public/multicall.ts
=> feat: add account param to multicall

src/celo/serializers.test.ts, src/utils/transaction/parseTransaction.test.ts, src/utils/transaction/parseTransaction.ts, src/utils/transaction/serializeTransaction.test.ts, src/zksync/serializers.test.ts, vectors/src/transaction.vectors.test.ts
=> fix: resolves #3649

.changeset/fast-flies-repeat.md, contracts/src/test/Delegation.sol, pnpm-lock.yaml, src/actions/public/call.test.ts, src/actions/public/call.ts, src/actions/public/estimateGas.test.ts, src/actions/public/getTransaction.test.ts, src/actions/public/simulateContract.test.ts, src/actions/wallet/sendTransaction.test.ts, src/actions/wallet/writeContract.test.ts
=> fix: propagate `authorizationList` on `call`

.changeset/moody-adults-fix.md, src/chains/definitions/flowMainnet.ts, src/chains/definitions/flowTestnet.ts
This PR changes Flow's block time to 800ms (scroll down https://flow.com/ to see)
=> Change Flow Mainnet & Testnet Block Time to 800ms

.changeset/new-mice-obey.md, src/chains/definitions/chiliz.ts, src/chains/definitions/morph.ts
multicall3 is now available on Chiliz and Morph
=> chore: list multicall3 on chains

.changeset/selfish-chicken-jam.md, src/chains/definitions/somniaTestnet.ts
@jxom Kindly review. Thank you.
=> Updated SomniaTestnet Multicallv3

site/pages/account-abstraction/accounts/smart/toMetaMaskSmartAccount.md
We've moved the documentation for the Delegation Toolkit. The old links(https://docs.gator.metamask.io/*) now redirect to  https://docs.metamask.io/delegation-toolkit, which will result in broken anchor links.
=> [MetaMaskSmartAccount] Update documentation links

site/pages/docs/contract/simulateContract.md
Fix `account` declaration in `site/pages/docs/contract/simulateContract.md`.
=> fix(docs): change account declaration to direct assignment

src/package.json
- Change the `repository` field in `src/package.json` to the standard object format.
- Add a `bugs` field for easier issue reporting.
- The standard object format for `repository` improves compatibility with npm, GitHub, and tooling.
- The `bugs` field provides a direct link for users to report issues.
- No functional code changes.
- Only improves package metadata for consumers and tooling.
=> optimize package.json metadata

src/chains/definitions/pulsechain.ts
while the url is correct, it does not behave the same as other block explorer urls. the functionality of the link provided in the update is similar to that of other block explorers
=> Fixup pulsechain explorer url

.changeset/stupid-mirrors-heal.md, src/chains/definitions/sovaSepolia.ts, src/chains/index.ts
=> Add sova sepolia

.changeset/tame-onions-explain.md, src/clients/transports/http.ts
Followup to https://github.com/wevm/viem/pull/3895 - expose fetch function override http transport
=> expose fetchFn override in http transport

.changeset/tame-buttons-sort.md, src/chains/definitions/sova.ts, src/chains/index.ts
=> Add Sophon mainnet

.changeset/dirty-trains-happen.md, src/chains/definitions/plasma.ts, src/chains/definitions/plasmaDevnet.ts, src/chains/definitions/plasmaTestnet.ts
Add's `multical3` for plasma chains
=> feat: add plasma multicall3 data
