wevm/viem

README.md

There is otherwise no direct link to the docs

docs: Make logo link to docs

---

site/docs/actions/test/dropTransaction.md

Prefer `Hash` over `$0x{string}` type in docs and link to the `Hash` glossary.

docs: fix drop transaction param type

---

site/docs/ethers-migration.md

- Fixed several `provider.listAcconts` typos in examples to `provider.listAccounts`
- Removed a duplicated Wallet section
- Fixed typo `decodeBase58` to `decodeBase64`

Fix typos and remove duplicate section in ethers-migration.md

---

package.json
pnpm-lock.yaml

Hello there, peer dependency `@algolia/client-search` could be ignored as per VitePress [doc](https://vitepress.vuejs.org/guide/getting-started#step-2-install-vitepress)

chore: ignore `@algolia/client-search` peer dependency

---

.github/CONTRIBUTING.md
site/docs/actions/test/setRpcUrl.md
site/docs/ethers-migration.md

Hey team 👋 
Bastien from Alchemy - quick doc update to future proof the Alchemy endpoints.
We're moving to `g.alchemy.com` instead of `alchemyapi.io`.
Epic stuff you're building 🚀

Update Alchemy URLs

---

site/.vitepress/theme/components/HomeSponsors.vue
site/index.md

Hi, just noticed a weird bug where toc has no padding:
And it's caused by the global style defined in home page:
```
<style>
.VPDoc .container {
max-width: 1120px !important;
}
.VPDoc .content {
max-width: 100% !important;
padding: 0px !important;
width: 100% !important;
}
</style>
```
In this fix, I've removed that global styles and wrapped the whole content inside a `div` with tailwindcss classes.
And here's the toc after the fix:

docs: fix home page

---

.changeset/polite-wasps-protect.md
src/utils/abi/decodeEventLog.test.ts
src/utils/abi/decodeEventLog.ts

fix: decoding event logs if constructor in abi

---

site/docs/utilities/pad.md

`pad` is documented as using `dir: left` as the default, but the example for `size` uses `dir: right` implicitly. This fixes it.

docs: fix pad example

---

.changeset/spotty-llamas-think.md
site/docs/contract/multicall.md
src/actions/ens/getEnsAddress.ts
src/actions/ens/getEnsName.ts
src/actions/public/multicall.test.ts
src/actions/public/multicall.ts
src/types/chain.ts
src/types/index.ts
src/utils/chain.test.ts
src/utils/chain.ts
src/utils/index.test.ts
src/utils/index.ts

Infers `multicallAddress` from client chain for `multicall` like we do in `getEnsName` and `getEnsAddress`.

feat: infer `multicallAddress` from client chain for `multicall`

---

.changeset/dull-windows-tease.md
src/types/log.ts

AFAICT, the `topics` property of logs in RPC responses can only be an array of hex strings. Elements of this array will never be null, and will never be an array of strings, so I think the type suggested here is more precise. See [this discussion](https://github.com/wagmi-dev/viem/discussions/163) and the [JSON-RPC spec](https://ethereum.github.io/execution-apis/api-documentation/) for more details.
To summarize:
1. The `topics` argument passed to `eth_getLogs` and `eth_newFilter` has the type `(Hex | Hex[] | null)[]`
2. The `topics` property of logs returned by `eth_getLogs`, `eth_getFilterLogs`, and `eth_getFilterChanges` has the type `Hex[]` (and has length <= 4)

fix: topics type for logs in rpc responses

---

site/docs/actions/public/call.md

I assume this line got included accidentally. I left the `focus` line count because the current one is accurate after removing this line.

docs: fix copy pasta

---

.changeset/warm-jokes-dress.md
src/errors/abi.test.ts
src/errors/abi.ts
src/errors/index.ts
src/index.test.ts
src/index.ts
src/utils/abi/decodeEventLog.test.ts
src/utils/abi/decodeEventLog.ts

fix: decodeEventLog topics mismatch

---

.github/workflows/release-canary.yml

Adds workflow to publish canary versions whenever `src/` (or the workflow file) is updated on `main`.

ci: add canary workflow

---

.changeset/early-worms-suffer.md
src/actions/public/watchBlockNumber.test.ts
src/actions/public/watchBlockNumber.ts
src/actions/public/watchBlocks.test.ts
src/actions/public/watchBlocks.ts

Some RPC Providers can be unreliable when polling for new block numbers. For example: the public Polygon RPC Provider can sometimes return block numbers in the past (that have already been seen before).
This PR adds a check to see if the next block number is greater than the previously seen block number.

fix: assert that next block is valid in `watchBlocks` & `watchBlockNumber`

---

.changeset/nervous-baboons-confess.md
site/docs/actions/public/watchEvent.md
src/actions/public/watchContractEvent.test.ts
src/actions/public/watchContractEvent.ts
src/actions/public/watchEvent.test.ts
src/actions/public/watchEvent.ts

Fixed an issue where `watchEvent` would not emit events on missed blocks for the `getLogs` fallback (when an RPC Provider does not support `getFilterChanges`).

fix: emit logs on missed blocks for `getLogs` fallback on `watchEvent`

---

.changeset/sixty-ties-pump.md
site/docs/actions/wallet/sendTransaction.md
site/docs/clients/wallet.md
site/docs/contract/writeContract.md
src/actions/wallet/sendTransaction.test.ts
src/actions/wallet/sendTransaction.ts
src/clients/createWalletClient.test.ts
src/clients/createWalletClient.ts
src/errors/chain.ts

We currently check if the **`chain` arg** on `sendTransaction` matches the wallet's active chain, but we don't check if the **wallet client `chain`** matches the wallet's active chain. Would be good to add it in.

feat: assert that client chain matches wallet's active chain

---

site/docs/abi/getAbiItem.md

Seems to be wrong based on the commented return block.

Fix getAbiItem item name in example

---

site/docs/abi/getAbiItem.md

Was trying to use this example and there are missing commas

fix: add missing commas in getAbiItem example

---

.changeset/gentle-peas-act.md
site/docs/actions/public/watchBlockNumber.md
site/docs/actions/public/watchBlocks.md
site/docs/actions/public/watchPendingTransactions.md
src/_test/index.ts
src/_test/utils.ts
src/actions/public/createPendingTransactionFilter.ts
src/actions/public/getFilterChanges.ts
src/actions/public/uninstallFilter.ts
src/actions/public/waitForTransactionReceipt.ts
src/actions/public/watchBlockNumber.test.ts
src/actions/public/watchBlockNumber.ts
src/actions/public/watchBlocks.test.ts
src/actions/public/watchBlocks.ts
src/actions/public/watchPendingTransactions.test.ts
src/actions/public/watchPendingTransactions.ts
src/clients/createPublicClient.ts
src/clients/decorators/public.test.ts
src/clients/decorators/public.ts
src/clients/transports/webSocket.ts
src/index.ts
src/types/index.ts
src/types/transport.ts

Added WebSocket `eth_subscribe` support `watchBlocks`, `watchBlockNumber`, and `watchPendingTransactions`.

feat: use ws subscriptions (`eth_subscribe`) for `watchBlocks`, `watchBlockNumber` & `watchPendingTransactions`

---

.changeset/cyan-rice-listen.md
site/docs/clients/transports/fallback.md
src/clients/createClient.ts
src/clients/transports/createTransport.ts
src/clients/transports/fallback.test.ts
src/clients/transports/fallback.ts
src/clients/transports/http.ts
src/clients/transports/webSocket.ts

Adds an automated ranking algorithm to rank Transports provided to the `fallback` Transport.
By default, each of the Transports passed to the `fallback` Transport are automatically ranked based on their **latency** & **stability** via a weighted moving score algorithm. 
Every 10 seconds (`interval`), the `fallback` Transport will ping each transport in the list. For the past 10 pings (`sampleCount`), they will be ranked based on if they responded (stability) and how fast they responded (latency). The algorithm applies a weight of `0.7` to the stability score, and a weight of `0.3` to the latency score to derive the final score which it is ranked on.
The Transport that has the best latency & stability score over the sample period is prioritized first.

feat: automated `fallback` ranking

---

.changeset/rich-numbers-crash.md
src/utils/abi/decodeFunctionData.ts

Fixes #262 
Not sure if you want to fix it like this as mentioned in the issue or whether you'd want to support constructors there.

fix: allow passing full contract abi to decodeFunctionData

---

site/docs/ethers-migration.md

- Extract `request` from the `simulateContract` returns to use as the `writeContract` arg in the "Writing to Contracts" section
- Fix typos
- Update highlighted lines

docs: Update migration from ethers guide

---

.changeset/quiet-toes-wave.md
src/utils/abi/decodeFunctionData.test.ts
src/utils/abi/decodeFunctionData.ts

I'm probably missing sth. here as I've not spent that much time with `abitype` yet. 
Btw., I cannot emphasize enough how much you guys are knocking it out of the park here). Test suite, type harness, etc. everything is such a pleasant experience to work with. Refactoring, writing tests, adding features, it's hands down the easiest / lowest barrier of entry experience I've ever had to contributing to a library.
ref: https://github.com/wagmi-dev/viem/discussions/264

feat: return discriminated union type from decodeFunctionData

---

.changeset/shy-vans-tan.md
src/utils/transaction/getTransactionType.test.ts
src/utils/transaction/getTransactionType.ts

Fixes #301 
The transaction object arrives at `getTransactionType` with `maxFeePerGas` and `maxPriorityFeePerGas` set as `undefined`. So we need to check that instead of checking whether the property exists or not.

fix: check whether tx properties are defined to derive tx type

---

.changeset/tender-tools-nail.md
src/actions/getContract.ts
src/types/contract.test-d.ts
src/types/contract.ts

I think this will help the story around type abstraction for consumers (ie. wagmi), as we will still be able to safely extract a `value` without other TS pain.

fix: make `GetValue` return `{ value?: never }` for contract functions that are not payable

---

.changeset/heavy-lies-type.md
src/adapters/ethers.test.ts
src/adapters/ethers.ts

fix: ethers adapter signTransaction properties

---

.changeset/spotty-chefs-glow.md
contracts/src/ERC20InvalidTransferEvent.sol
src/_test/index.ts
src/_test/utils.ts
src/actions/public/getFilterChanges.test.ts
src/actions/public/getFilterChanges.ts
src/actions/public/getFilterLogs.test.ts
src/actions/public/getFilterLogs.ts
src/actions/public/getLogs.test.ts
src/actions/public/getLogs.ts
src/actions/public/multicall.test.ts
src/errors/abi.test.ts
src/errors/abi.ts
src/errors/index.ts
src/utils/abi/decodeAbiParameters.test.ts
src/utils/abi/decodeAbiParameters.ts
src/utils/abi/decodeEventLog.test.ts
src/utils/abi/decodeEventLog.ts
src/utils/abi/formatAbiItem.test.ts
src/utils/abi/formatAbiItem.ts
src/utils/abi/index.test.ts
src/utils/abi/index.ts
src/utils/index.test.ts
src/utils/index.ts

Fixes #323.
- Skips event logs that do not conform to the given ABI filter
- Adds better error messaging for when ABI decoding `data` size is too short
- Adds better error messaging for when there is a mismatch between non-indexed arguments in the event ABI

fix: skip invalid logs

---

.changeset/eleven-donkeys-lay.md
src/errors/request.test.ts
src/errors/request.ts

As `UserRejectedRequestError` and `SwitchChainError` could come from another source (not just RPC – could be WalletConnect, Coinbase SDK, etc), making it so you can pass an arbitrary cause to these errors.

feat: tweaked error inheritence for `UserRejectedRequestError` & `SwitchChainError`

---

tsconfig.json

This causes `vscode` (and hopefully also other IDEs), to autocomplete type imports properly. We are not setting it in the `tsconfig.base.json` config because we don't want this for the `commonjs` build target.
So, setting it in `tsconfig.json` causes it to be considered by IDEs while still supporting the `commonjs` build target & setting it explicitly (using `--verabitmModuleSyntax`) for the ESM build target.

chore: use verbatim module syntax in tsconfig.json

---

tsconfig.base.json

TIL: These two are not compatible (isolatedModules & verbatimModuleSyntax).

chore: remove isolated modules

---

.changeset/funny-cars-provide.md
src/actions/public/watchBlocks.ts
src/actions/public/watchPendingTransactions.ts

Fixes #342 
Fixes #341 
This fixes the aforementioned issues. However (and without having looked into it & thought about it further yet), I think it would be better to remove knowledge of these transport specific options from the client completely. To me that looks like reversed coupling.

fix: conditional types for poll options

---

.changeset/thick-mangos-shave.md
src/utils/rpc.ts

Should we maybe configure different vitest environments (vitest supports jsdom, node, edge, etc.) in a test matrix in CI to ensure support for edge in the future?

refactor: use async import for isomorphic-ws to support edge runtime

---

.changeset/wild-toys-kiss.md
src/actions/public/call.ts
src/actions/public/createContractEventFilter.test.ts
src/actions/public/createEventFilter.test.ts
src/actions/public/estimateGas.ts
src/actions/public/getBlock.ts
src/actions/public/getBlockTransactionCount.ts
src/actions/public/getChainId.ts
src/actions/public/getGasPrice.ts
src/actions/public/getTransactionCount.ts
src/actions/public/uninstallFilter.test.ts
src/clients/createClient.test.ts
src/clients/createClient.ts
src/clients/createPublicClient.test.ts
src/clients/createPublicClient.ts
src/clients/createTestClient.test.ts
src/clients/createTestClient.ts
src/clients/createWalletClient.test.ts
src/clients/createWalletClient.ts
src/clients/transports/createTransport.test.ts
src/clients/transports/createTransport.ts
src/clients/transports/custom.test.ts
src/clients/transports/custom.ts
src/clients/transports/fallback.ts
src/index.ts
src/types/eip1193.test-d.ts
src/types/eip1193.ts
src/types/filter.ts
src/utils/filters/createFilterRequestScope.ts

Makes the EIP1193 `request` function more flexible (ie. can now unionize it & use it w/o a function). Will be useful for batch JSON-RPC and secret project.

refactor: eip1193 request types

---

.changeset/pretty-carrots-grin.md
src/actions/wallet/writeContract.ts
src/clients/createClient.test-d.ts

Fixes protected action types for `writeContract`

fix: protected action types

---

.changeset/tidy-mice-switch.md
pnpm-lock.yaml
src/package.json
src/utils/signature/hashTypedData.test.ts

This PR updates the `abitype` version and adds a test to validate the new type for `chainId` in the context of EIP712.

chore: `abitype` 1.0.7 and test using `bigint` for `chainId` in `hashTypedData`

---

.changeset/ten-rockets-repeat.md
src/account-abstraction/accounts/implementations/toSoladySmartAccount.ts
src/experimental/erc7739/actions/signTypedData.test.ts
src/experimental/erc7739/actions/signTypedData.ts
src/experimental/erc7739/utils/hashTypedData.test.ts
src/experimental/erc7739/utils/hashTypedData.ts

Sync latest 7739 changes.
Ref: https://github.com/Vectorized/solady/pull/1130, https://github.com/ethereum/ERCs/pull/687

feat: sync 7739

---

.changeset/cool-tips-lick.md
src/index.test.ts
src/index.ts
src/utils/index.ts
src/utils/signature/hashTypedData.ts

It is not possible to import `hashStruct`. This method is useful should a contract not follow EIP-712.
This exports `hashStruct` and the associated `HashStructErrorType`.
Note: there is also an [open discussion requesting this change](https://github.com/wevm/viem/discussions/761).
- Export `HashStructErrorType`
- Import `hashStruct` and `HashStructErrorType` in both index and `/utils`

fix: export `hashStruct`

---

.changeset/fluffy-bears-kick.md
site/pages/docs/contract/estimateContractGas.md
src/actions/public/estimateContractGas.test.ts
src/actions/public/estimateContractGas.ts

This PR adds the `dataSuffix` parameter to `estimateContractGas`, since this parameter impacts gas cost if it is used in `writeContract`. The implementation is consistent with those of `writeContract` and `simulateContract`, the docs were updated and a test is added.

Add dataSuffix arg to estimateContractGas

---

src/chains/definitions/plume.ts
src/chains/definitions/plumeDevnet.ts

Multicall3 on Plume Devnet: https://test-explorer.plumenetwork.xyz/address/0xcA11bde05977b3631167028862bE2a173976CA11
Multicall3 on Plume Mainnet: https://phoenix-explorer.plumenetwork.xyz/address/0xcA11bde05977b3631167028862bE2a173976CA11

feat: add multicall3 contracts to Plume

---

src/chains/index.ts

Fix incorrect deprecated comment location (https://github.com/wevm/viem/pull/2897/files#diff-bcdf494bd48667265e1dcbf43c7054c780c64d2c940330be7c5fdaed5597e1a7R196)

Fix klaytn deprecated comment

---

.changeset/tall-pets-impress.md
src/zksync/actions/sendEip712Transaction.ts
src/zksync/actions/signEip712Transaction.test.ts
src/zksync/actions/signEip712Transaction.ts
src/zksync/decorators/eip712.test.ts
test/src/zksync.ts

Fix the account hoisting for `signEip712Transaction` and `sendEip712Transaction`. The actions only took account from parameters and did not check the account from client.

ZKsync: account hoisting fix for `signEip712Transaction` and `sendEip712Transaction`

---

.changeset/honest-apricots-jump.md
site/pages/zksync/actions/getL1TokenAddress.md
site/pages/zksync/actions/getL2TokenAddress.md
site/sidebar.ts
src/zksync/actions/getL1TokenAddress.test.ts
src/zksync/actions/getL1TokenAddress.ts
src/zksync/actions/getL2TokenAddress.test.ts
src/zksync/actions/getL2TokenAddress.ts
src/zksync/constants/abis.ts
src/zksync/decorators/publicL2.test.ts
src/zksync/decorators/publicL2.ts
src/zksync/index.ts

To enable seamless bridging of assets across chains, it is necessary to retrieve the corresponding token address on the other chain for a given asset. This involves implementing two public actions to facilitate the mapping between L1 and L2 token addresses.
Implementend the following public actions:
`getL1TokensAddress()` - returns the L1 token address equivalent for a L2 token address.
`getL2TokensAddress()` - returns the L2 token address equivalent for a L1 token address.

ZKsync: provide public actions for fetching token addresses on L1 and L2 chains

---

src/README.md

Etherscan changed their lookup link and current link was throwing an error

Fix etherscan ens lookup link in support section from Readme

---

.changeset/brave-cooks-carry.md
src/actions/wallet/prepareTransactionRequest.ts

Fixes [#3142](https://github.com/wevm/viem/issues/3142) by deferring the nonce consumption in `prepareTransactionRequest` until after gas estimation succeeds, avoiding a nonce gap when gas estimation fails.
- Reordered logic so `nonceManager.consume(...)` is called after gas estimation
- Added a changeset for a patch release
- Old behavior: We called `nonceManager.consume(...)` before gas estimation, so if gas estimation failed, we never broadcast a transaction but had already incremented the nonce.
- New behavior: We’ve reordered the logic in `prepareTransactionRequest` so that all fees and gas estimation happen first. Only if those steps succeed do we call `consume(...)` from the nonce manager. This way, no extra nonce is burned on failure.
- Alternative considered: Rolling back the …

fix: avoid nonce gap in nonceManager (#3142)

---

.changeset/sixty-mice-build.md
pnpm-lock.yaml
src/actions/public/waitForTransactionReceipt.test.ts
src/actions/public/waitForTransactionReceipt.ts

This PR corrects the logic when identifying the reason associated with a replaced transaction.
Before, `repriced` was used to classify any replacement transaction with the same value and recipient as the original, but I believe it should also check the transaction `data` to ensure that if the transaction was a contract call, the function data has also not changed.
Therefore, I added a check to ensure the original and replacement transaction share the same contract call data before classifying a replacement as `repriced`
Added relevant tests, but had a bit of trouble running the test suite.

fix: correct logic for identifying repriced transactions

---

.changeset/five-timers-decide.md
src/chains/definitions/berachainTestnetbArtio.ts

Add ensRegistry and ensUniversalResolver to Berachain Bartio using Beranames => https://x.com/beranames
Contracts have been verified as requested by contributing guidelines. 
Registry => https://bartio.beratrail.io/address/0xB0eef18971290b333450586D33dcA6cE122651D2
Universal Resolver => https://bartio.beratrail.io/address/0x41692Ef1EA0C79E6b73077E4A67572D2BDbD7057
Documentation => https://docs.beranames.com

Add ENS (BNS) to berachain bartio

---

src/utils/signature/hashTypedData.test.ts
src/utils/typedData.ts

This modification was missing after `bigint` was added here https://github.com/wevm/abitype/commit/ee60e674458824fccfd22874a8815075cc5b269a so the hash was not calculated correctly in this case.

fix(EIP712): `domain`'s `chainId` was not getting the types correctly when `bigint`

---

.changeset/fuzzy-scissors-carry.md
site/pages/zksync/actions/withdraw.md
site/sidebar.ts
src/zksync/actions/withdraw.test.ts
src/zksync/actions/withdraw.ts
src/zksync/constants/abis.ts
src/zksync/constants/address.ts
src/zksync/decorators/walletL2.test.ts
src/zksync/decorators/walletL2.ts
src/zksync/index.ts

Introduce the `withdraw` action, enabling  withdrawing assets from L2 to L1.

ZKsync: add `withdraw` action

---

.changeset/shaggy-taxis-dance.md
package.json
site/pages/docs/clients/transports/http.md
site/pages/docs/clients/transports/ipc.md
site/pages/docs/clients/transports/websocket.md
src/clients/transports/createTransport.ts
src/clients/transports/custom.ts
src/clients/transports/fallback.test.ts
src/clients/transports/http.test.ts
src/clients/transports/http.ts
src/clients/transports/ipc.ts
src/clients/transports/webSocket.ts
src/errors/rpc.test.ts
src/errors/rpc.ts
src/types/eip1193.ts
src/utils/buildRequest.test.ts
src/utils/buildRequest.ts

feat: add `methods.{include|exclude}` on transport options

---

.changeset/quiet-carpets-raise.md
src/chains/definitions/creditCoin3Testnet.ts

Sorry there was a typo in this [PR](https://github.com/wevm/viem/pull/3254).

Remove unnecessary double quote in creditcoin3 testnet rpcUrls

---

.changeset/heavy-lies-attend.md
src/utils/buildRequest.ts

Found this while exploring solutions to https://github.com/wevm/viem/discussions/3274. Doesn't seem necessary to do the extra work of hashing this internal ID when `Map` likely already hashes keys in memory.

feat: don't hash request ID

---

.changeset/empty-kangaroos-join.md
src/chains/definitions/wmcTestnet.ts
src/chains/index.ts

**Description:**
This PR adds the configuration for the **WMC Testnet** chain to the Viem project. The configuration includes:
- Chain ID: **42070**
- RPC URL: https://rpc-testnet-base.worldmobile.net
- Native Currency:
- Name: **WMTx**
- Symbol: **WMTx**
- Decimals: **18**
- Block Explorer:
- Name: **WMC Explorer**
- URL: https://explorer2-base-testnet.worldmobile.net
This chain is a testnet and has been configured as such in the testnet flag.
**Changes Made:**
- Added a new file wmcTestnet.ts to src/chains/definitions/.
- Exported the chain in src/chains/index.ts.
**Why this PR is important:**
Adding the **WMC Testnet** to Viem enables developers to integrate their applications with the chain using the Viem library.

Added WMC Testnet chain configuration

---

site/pages/docs/actions/public/simulate.md

https://viem.sh/docs/actions/public/simulate#contract-calls 
Fixed the issue where hovering over parseAbi showed any type, ensuring the correct type is displayed.

Added the missing parseAbi function import

---

.changeset/dry-ducks-love.md
src/chains/definitions/berachain.ts

This PR adds the multicall3 address to the brand new Berachain Mainnet. It was included in the genesis file so it's available from block 0. 
Thank you Bears! 🐻

Adds multicall to berachain mainnet

---

.changeset/beige-chicken-approve.md
src/chains/definitions/metis.ts
src/chains/definitions/metisSepolia.ts
src/chains/index.ts

- Adds Metis Sepolia testnet chain configuration
- Deprecates Metis Goerli chain in favor of Metis Sepolia
- Updates chain exports in index.ts
- Added src/chains/definitions/metisSepolia.ts
- Added deprecation notice for metisGoerli
- Updated exports in index.ts to include metisSepolia
- Chain ID: 59902
- RPC Endpoint: https://sepolia.metis.io/?owner=1088
- Block Explorer: https://sepolia.explorer.metisdevops.link

chore: add changeset for Metis Sepolia

---

.changeset/lovely-dodos-sit.md
src/chains/definitions/berachain.ts

Add ensRegistry and ensUniversalResolver to Berachain Bartio using Beranames => https://beranames.com
Contracts have been verified as requested by contributing guidelines.
Registry => https://berascan.com/address/0x5b22280886a2f5e09a49bea7e320eab0e5320e28
Universal Resolver => https://berascan.com/address/0xddfb18888a9466688235887dec2a10c4f5effee9
Documentation => https://docs.beranames.com/
Reference to testnet PR => https://github.com/wevm/viem/pull/3101

Add ens to berachain

---

site/pages/account-abstraction/actions/bundler/waitForUserOperationReceipt.md

https://viem.sh/account-abstraction/actions/bundler/waitForUserOperationReceipt#getuseroperationreceipt
The title on this page should be `waitForUserOperationReceipt`

fix(docs): Update waitForUserOperationReceipt page title to correctly reflect page content

---

.changeset/quiet-bees-leave.md
src/chains/definitions/unichain.ts

Unichain currency name should be `Ether` instead of `Unichain`.

fix: unichain currency name

---

.changeset/short-tools-complain.md
src/chains/definitions/donatuz.ts

- Fixes Donatuz network RPC URL which was missing an `h`

fix: Donatuz rpc url

---

.changeset/real-eels-shop.md
src/chains/definitions/berachainTestnet.ts

Added the Multicall3 contract address to the viem configuration for use in `Berachain Artio`. This ensures support for batch contract calls with improved efficiency.

Add multicall3 contract to Berachain Artio

---

.changeset/twenty-moons-bathe.md
src/chains/definitions/storyAeneid.ts
src/chains/index.ts

feat: Add Story Aeneid chain

---

.changeset/selfish-pandas-smoke.md
src/chains/definitions/worldchain.ts

Official addresses: https://docs.world.org/world-chain/developers/world-chain-contracts#ethereum-mainnet

fix: `disputaGameFactory` contract address in World Chain

---

.changeset/perfect-shoes-flow.md
site/pages/zksync/actions/finalizeWithdrawal.md
site/sidebar.ts
src/zksync/actions/finalizeWithdrawal.test.ts
src/zksync/actions/finalizeWithdrawal.ts
src/zksync/constants/abis.ts
src/zksync/constants/address.ts
src/zksync/decorators/walletL1.test.ts
src/zksync/decorators/walletL1.ts
src/zksync/errors/bridge.test.ts
src/zksync/errors/bridge.ts
src/zksync/index.ts
src/zksync/utils/bridge/getWithdrawalL2ToL1Log.test.ts
src/zksync/utils/bridge/getWithdrawalL2ToL1Log.ts
src/zksync/utils/bridge/getWithdrawalLog.test.ts
src/zksync/utils/bridge/getWithdrawalLog.ts
test/src/zksync.ts

Introduce the  `finalizeWithdrawal` action, enabling finalization of withdrawal transaction on L1.

ZKsync: add `finalizeWithdrawal` action

---

.changeset/cold-teachers-sell.md
src/chains/definitions/form.ts
src/chains/definitions/formTestnet.ts

Add Form and Form Testnet chains

---

.changeset/calm-socks-remain.md
src/utils/rpc/webSocket.ts

Some providers, return error responses as strings instead of JSON objects. For example, getBlock.io returns "rate limit reached" as a plain string, causing a SyntaxError when attempting to parse it as JSON.

Handle Non-JSON Error Responses from Providers

---

.changeset/nine-mails-lie.md
src/clients/transports/http.test.ts
src/clients/transports/http.ts
src/types/eip1193.ts
src/utils/rpc/webSocket.ts

This allows the transport to be used in a lower level mode suitable for situations like a proxy.
The main alternative I explored was catching errors and reconstructing raw errors from `RpcRequestError`. This is not ideal in a high throughput production environment since creating stack traces incurs an unneeded performance cost.
If supportive of direction will round with docs.

Add raw option to http transport

---

src/clients/decorators/test.ts

The JSDocs for the test client's `sendUnsignedTransaction` are currently incorrect, seeminly having some values (description & link to dopcumentation website) mistakenly copied from the docs for `getTxpoolContent`. I noticed this while trying to call `sendUnsignedTransaction` and seeing confusing messaging in my IDE.
This PR fixes the JSDoc comments, linking to the correct page and fixing the description. I had a look around and could not find any other instances of such errors, so it seems to be an isolated incident.

Fix incorrect JSDoc comments for sendUnsignedTransaction

---

.changeset/slow-hornets-like.md
src/chains/definitions/telos.ts
src/chains/definitions/telosTestnet.ts

This PR is to update the RPCs for TelosEVM and TelosEVM Testnet to the new URLs that leverage the newer 2.0 reth based RPCs.

Update Telos RPCs

---

.changeset/two-bears-warn.md
package.json
site/pages/docs/clients/transports/fallback.md
src/clients/transports/fallback.test.ts
src/clients/transports/fallback.ts
src/index.ts

Adds a `shouldThrow` option to the fallback transport, to customize which errors trigger a fallback vs a throw. We are using this so a contract error (eg a failed `require` in contract code) does not trigger the fallback and fails immediately.
Happy to add some tests if this contribution makes sense.

feat(transport): Add shouldThrow as an option to fallback transport

---

.changeset/gorgeous-eggs-count.md
src/chains/definitions/planq.ts

This PR adds additional RPCs to Planq Mainnet and as well adds the deployed multicall3 address to the config.

Planq Network: Add additional RPCs, add multicall3 address

---

src/chains/definitions/sonic.ts

Remove trailing slash from Sonic default block explorer url

fix: Sonic block explorer url

---

.changeset/orange-seahorses-shout.md
src/chains/definitions/plume.ts
src/chains/definitions/plumeMainnet.ts
src/chains/index.ts

Users on the existing Plume private mainnet with chain ID 98865 will be migrated over to the new Plume private mainnet over the next several weeks, before mark the existing Plume private mainnet as deprecated.

feat: add Plume Mainnet

---

.changeset/chilled-radios-clap.md
src/utils/ccip.ts

- add `toLowerCase()` to `"sender"` (I left `"data"` as-is)
Reference: https://eips.ethereum.org/EIPS/eip-3668
> Each URL may include two substitution parameters, {sender} and {data}. Before a call is made to the URL, sender is replaced with the lowercase 0x-prefixed hexadecimal formatted sender parameter, and data is replaced by the 0x-prefixed hexadecimal formatted callData parameter.

bug: EIP-3668 `sender` must be lowercase

---

.changeset/metal-pianos-cover.md
src/utils/formatters/transactionRequest.ts

Format to not have leading zero digits in authorizationList's r and s values
Fixes #3454

Fix for #3454

---

.changeset/quiet-chicken-joke.md
src/chains/definitions/happychainTestnet.ts

Updates deprecated Happychain Testnet URLS for RPC endpoint and explorer

fix: update happychain testnet deprecated urls

---

.changeset/plenty-mayflies-leave.md
.gitignore
src/index.ts

Without these, something as simple as the following results in a compiler error in projects that depend on viem:
```ts export const createReadClient = () => {
return createWalletClient({ chain: mainnet, transport: custom(ethereum), cacheTime }).extend(publicActions)
}
```
This is because `publicActions`'s return type depends on `CreateAccessList` and `Simulate*`.
Note: The current mechanism of manually adding these things to `index.ts` seems ripe for this class of failure.  It feels like either an alternative re-export system should be used (e.g., `export * from '...'`) or some automation should be built to ensure that everything is properly re-exported.
I also added `.pnpm-store` to `.gitignore` because with out it this commit was going to be a bajillion files large as `pnpn install` …

Adds missing re-exports.

---

src/chains/definitions/etherlinkTestnet.ts

Correct of the Etherlink testnet block explorer url.

Correct etherlink testnet block explorer url

---

.changeset/shaggy-ducks-give.md
site/pages/docs/ethers-migration.mdx
site/pages/docs/getting-started.mdx
site/pages/experimental.mdx
site/pages/op-stack.mdx
src/chains/definitions/bsc.ts
src/chains/definitions/btr.ts
src/chains/definitions/chiliz.ts
src/chains/definitions/corn.ts
src/chains/definitions/cornTestnet.ts
src/chains/definitions/fantom.ts
src/chains/definitions/goerli.ts
src/chains/definitions/harmonyOne.ts
src/chains/definitions/polygonMumbai.ts
src/chains/definitions/swellchain.ts
src/utils/chain/defineChain.test.ts

ankr rugging public rpc urls, thirdweb better anyway
https://x.com/ankr/status/1901666598257401881

fix: ankr => thirdweb for default rpc urls

---

.changeset/something.md
src/chains/definitions/sonicBlazeTestnet.ts

Added the Multicall3 contract address to the viem configuration for use in Sonic Blaze Testnet.

Add multicall3 contract to Sonic Blaze Testnet

---

.changeset/stale-cheetahs-travel.md
src/chains/definitions/xrplevmTestnet.ts
src/chains/index.ts

- Adds a new chain file `xrplEvmTestnet.ts` under `src/chains/definitions/`.
- Sets `chainId` to **1449000**, names it “XRPLEVM Testnet”, and includes RPC URLs, explorer, and `XRP` as native currency.
- Exports `xrplEvmTestnet` in `src/chains/index.ts`.
- Adds a patch changeset: “Added XRPLEVM Testnet chain.”
> **Verification**:
> - Chain tested locally in dev environment to confirm RPC and explorer availability.  
> - Multicall3 deployed manually (gas usage ~1.6M) at `0x82Cc144D7d0AD4B1c27cb41420e82b82Ad6e9B31`.  
> 
> **Any additional notes**:
> - The pre-signed Multicall3 transaction is not possible due to higher gas usage (over 1M).  
> - Please let me know if there are any adjustments needed!
---

add XRPLEVM Testnet

---

src/chains/definitions/plume.ts
src/chains/definitions/plumeDevnet.ts
src/chains/definitions/plumeMainnet.ts
src/chains/definitions/plumeSepolia.ts
src/chains/definitions/plumeTestnet.ts

add multicall deployments to Plume networks

---

.changeset/shaggy-seas-walk.md
src/chains/definitions/hoodi.ts

This pull request includes a small but important change to the `src/chains/definitions/hoodi.ts` file. The change updates the default block explorer for the `hoodi` chain.
* [`src/chains/definitions/hoodi.ts`](diffhunk://#diff-a981608fda38859c68217e9202435d039fc69639c309f7811f761ece07f89331L14-R15): Changed the default block explorer from Blockscout to Etherscan.

fix: update block explorer for Hoodi chain from Blockscout to Etherscan

---

.changeset/tough-apples-occur.md
src/chains/definitions/ink.ts

Multicall3 contract is listed in Ink docs [here](https://docs.inkonchain.com/useful-information/contracts#ink-mainnet-1), deployment block is set as `0` since the contract is a "preinstall" from the OP stack ([see here](https://specs.optimism.io/protocol/preinstalls.html)).

Add Multicall3 address to Ink Mainnet

---

.changeset/six-donuts-matter.md
src/chains/definitions/confluxESpace.ts
src/chains/definitions/confluxESpaceTestnet.ts

ConfluxScan is using new domain link. This pull request updates the conflux explorer link.
Check official announcement here:
https://forum.conflux.fun/t/confluxscan-domain-update-announcement-march-28-2025/21920

fix: update ConfluxScan URLs for mainnet and testnet

---

.changeset/short-scissors-matter.md
src/celo/fees.test.ts
src/celo/fees.ts

This removes the L2 chain detection check in Celo's fee estimation logic following the successful hardfork. 
Previously, the code would check if the chain was L2 by looking for code at the proxy admin address to determine which fee calculation method to use. This distinction is no longer needed and eliminates an extra `eth_getCode` request during fee estimation.
Changes:
- Removed `isCel2` function and L2 detection logic
- Simplified fee calculation to use a single formula
- Updated tests to remove L1/L2 specific cases

fix(celo): remove L2 check in fee estimation following the successful hardfork

---

.changeset/metal-moose-report.md
src/clients/createPublicClient.test.ts
src/clients/transports/webSocket.ts

Fixes #3521
This will ensure that the `keepAlive` and `reconnect` parameters are passed through to the underlying implementation in all cases.
Signed-off-by: Peter Somogyvari <peter.metz@unarin.com>

fix: `webSocket()` transport ignores `keepAlive`, `reconnect`

---

site/pages/docs/abi/decodeAbiParameters.md

This PR adds a simple example for how to decode `bytes` types using `decodeAbiParameters` to prevent issues like https://github.com/wevm/viem/issues/3524 from being reported again.

docs: add simple bytes example

---

.changeset/fair-donuts-fry.md
src/chains/definitions/linea.ts
src/chains/definitions/lineaSepolia.ts

Add `ensRegistry` and `ensUniversalResolver` to Linea Sepolia and Mainnet using Linea Name Service: https://names.linea.build
Contracts have been verified as requested by contributing guidelines.
Contracts Addresses:
1. Linea Sepolia
1. EnsRegistry: https://sepolia.lineascan.build/address/0x5B2636F0f2137B4aE722C01dd5122D7d3e9541f7
2. EnsUniversalResolver: https://sepolia.lineascan.build/address/0x72560a31B3DAEE82B984a7F51c6b3b1bb7CC9F50
2. Linea Mainnet
1. EnsRegistry: https://lineascan.build/address/0x50130b669B28C339991d8676FA73CF122a121267
2. EnsUniversalResolver: https://lineascan.build/address/0x3aA974fb3f8C1E02796048BDCdeD79e9D53a6965
Documentation: https://support.linea.build/explore/ens

Add ENS to Linea Sepolia and Mainnet

---

.changeset/shy-adults-cover.md
.changeset/ten-pets-reply.md
site/pages/experimental/eip5792/getCallsStatus.mdx
site/pages/experimental/eip5792/getCapabilities.mdx
site/pages/experimental/eip5792/sendCalls.mdx
site/pages/experimental/eip5792/waitForCallsStatus.mdx
src/experimental/eip5792/actions/getCallsStatus.test.ts
src/experimental/eip5792/actions/getCallsStatus.ts
src/experimental/eip5792/actions/getCapabilities.test.ts
src/experimental/eip5792/actions/getCapabilities.ts
src/experimental/eip5792/actions/sendCalls.test.ts
src/experimental/eip5792/actions/sendCalls.ts
src/experimental/eip5792/actions/waitForCallsStatus.test.ts
src/experimental/eip5792/actions/waitForCallsStatus.ts
src/experimental/eip5792/actions/writeContracts.test.ts
src/experimental/eip5792/decorators/eip5792.test.ts
src/index.ts
src/types/eip1193.ts

feat: sync to latest EIP-5792 spec

---

.changeset/olive-kings-burn.md
src/op-stack/actions/getWithdrawalStatus.ts

The Optimism Portal contract can revert with `Unproven()` after a state transition root on L2 has been processed on L1 but before a withdrawal proof has been submitted. I believe that, in the context of `getWithdrawalStatus()`, since we first check the dispute game factory to see whether a state proof has been made which would include the withdrawal initiated at the input `l2BlockNumber`, if `disputeGameResult` is _not_ rejected and the withdrawal status result _is_ rejected due to an `Unproven()` revert, then the withdrawal _is_ ready to be proven.

fix(op-stack): `unproven` is contextually a ready-to-prove case

---

site/pages/op-stack/actions/initiateWithdrawal.md

The `config.ts` section of the [Usage docs for initiateWithdrawal](https://viem.sh/op-stack/actions/initiateWithdrawal#usage) shows the `walletClientL2` to be created with the `mainnet` chain. However, this is incorrect because the `chain` shall be an L2. This is even stated below, in the documentation for the `chain` property

docs: fix wrong chain in initiateWitdrawal.md

---

.changeset/healthy-crews-appear.md
src/chains/definitions/hoodi.ts

Added multicall3 contract to Hoodi chain
This PR adds the multicall3 contract address to the Hoodi chain definition, enabling multicall functionality for the chain.
Changes:
- Added multicall3 contract configuration to Hoodi chain definition
- Contract address: 0xca11bde05977b3631167028862be2a173976ca11

feat: add multicall3 contract to Hoodi chain

---

src/chains/definitions/peaq.ts

We've done extensive testing while supporting Peaq at Aragon and the publicnode endpoint has been significantly more reliable.
Transactions with the onfinality endpoint have a much higher chance of failing.

Peaq: Change order of public RPCs

---

site/pages/docs/actions/public/estimateGas.md

This documentation update is for the `estimateGas` `data` parameter.  It adds a reference to `encodeFunctionData` to provide guidance on its usage.

add note about using encodeFunctionData to data of estimateGas

---

.changeset/two-bees-build.md
src/chains/definitions/newton.ts

Fix typo in **Newton** chain definition.  Default rpc url contains an extra letter in protocol _hhttps_.

fix: newton chain rpc url typo

---

.changeset/thin-steaks-knock.md
src/chains/definitions/metis.ts
src/chains/definitions/metisSepolia.ts

Fixed misconfigured `rpcUrls` for **Metis** and **Metis Sepolia** chains.  `wss://` websocket urls were incorrectly placed in the `rpcUrls.default.http` property along with `http` rpc urls.  This  was causing issues when adding or switching to Metis chains.
`MetaMask - RPC Error: Expected an array with at least one valid string HTTPS url 'rpcUrls', Received:
wss://metis-sepolia-rpc.publicnode.com `

fix: correct RPC URL configuration for Metis chains

---

.changeset/brown-ducks-smell.md
pnpm-lock.yaml
src/chains/definitions/skale/calypso.ts
src/chains/definitions/skale/europa.ts
src/chains/definitions/skale/exorde.ts
src/chains/definitions/skale/nebula.ts
src/chains/definitions/skale/titan.ts
src/chains/definitions/skale/titanTestnet.ts
src/chains/index.ts

- Deprecates Unused SKALE Chains: Razor, Human Protocol, CryptoColosseum
- Simplifies Names for SKALE Chains

Update and Deprecate SKALE Network Chains

---

.changeset/brown-schools-care.md
src/account-abstraction/accounts/implementations/toCoinbaseSmartAccount.test.ts
src/account-abstraction/accounts/implementations/toCoinbaseSmartAccount.ts

feat: prefer `signTypedData` on owners for `toCoinbaseSmartWallet`

---

site/pages/op-stack/actions/estimateFinalizeWithdrawalGas.md
site/pages/op-stack/actions/estimateProveWithdrawalGas.md
site/pages/op-stack/actions/getTimeToFinalize.md
site/pages/op-stack/actions/getTimeToProve.md
site/pages/op-stack/actions/getWithdrawalStatus.md

This pull request updates several markdown documentation files by replacing outdated contract links to the correct OptimismPortal2.sol and L2OutputOracle.sol locations. These updates improve documentation accuracy and ensure consistency with the current state of the Optimism codebase.

fix: update Optimism contract doc links for accuracy

---

.changeset/thick-carrots-refuse.md
pnpm-lock.yaml
src/package.json

Due to viem pinning dependencies, noble didn't get deduped. This PR simply bumps noble to the versions used in ox

fix: dedupe noble

---

site/pages/docs/actions/wallet/prepareTransactionRequest.md
site/pages/docs/actions/wallet/sendTransaction.md
site/pages/docs/actions/wallet/signTransaction.md
site/pages/docs/actions/wallet/switchChain.md
src/actions/wallet/switchChain.ts

Fix docs regarding the `wallet_switchEthereumChain` method. You can easily verify that is should start with "wallet" instead of "eth".

Fix docs regarding the `wallet_switchEthereumChain` method.

---

.changeset/khaki-nails-eat.md
src/actions/wallet/sendTransaction.ts

Currently when using `sendTransaction` with MetaMask as the client, if `accessList` is specified alongside `maxFeePerGas` and `maxPriorityFeePerGas` the call will fail. This is due to MetaMask incorrectly deriving a transaction type of `0x01` (see https://github.com/MetaMask/core/issues/5720), but `sendTransaction` can easily be tweaked to ensure compatibility with all existing MetaMask clients. Making the transaction type explicit ensures that it isn't derived, and bypasses the issue entirely.
Changes:
- Added `type` to the formatted transaction in `sendTransaction`.

feat: add transaction type to formatted transaction in `sendTransaction`

---

.changeset/purple-dingos-swim.md
src/chains/definitions/fraxtal.ts
src/chains/definitions/fraxtalTestnet.ts

This PR updates the gas token for both the Fraxtal mainnet and Fraxtal testnet from the previous token to FRAX, aligning with the latest network configuration and token standard.
Changes:
Updated gas token symbol to FRAX for Fraxtal mainnet.
Updated gas token symbol to FRAX for Fraxtal testnet.
Reason for Change:
Fraxtal has transitioned to using FRAX as the native gas token on both mainnet and testnet. This update ensures consistency with the current network specifications and prevents confusion or misconfigurations.

Update Fraxtal and Fraxtal testnet gas token to FRAX 

---

.changeset/breezy-grapes-appear.md
src/actions/wallet/getCapabilities.ts
src/clients/decorators/wallet.ts
src/types/eip1193.ts

fix: `wallet_getCapabilities` params

---

src/chains/definitions/plumeMainnet.ts
src/chains/definitions/plumeSepolia.ts

Plume is migrating all of our RPC URLs from https://phoenix-rpc.plumenetwork.xyz to https://rpc.plume.org.

update plumenetwork.xyz to plume.org

---

.changeset/spotty-beds-grow.md
src/actions/public/watchBlocks.ts
src/types/register.ts

This currently doesn't work when `block.number` is `0` (boolish false)

make watchBlocks with `emitMissed` work from genesis block

---

.changeset/thick-mayflies-itch.md
src/celo/formatters.test.ts
src/celo/formatters.ts
src/celo/types.ts

Following the migration of celo to L2 this PR removes any differences in block structure which are no longer true.
https://specs.celo.org/l2_migration.html?highlight=block#l2-block-structure states that "[celo's] block structure fully up to date with Ethereum’s block structure." This PR reflects that in viems block types

remove celo peculiarities from block structure

---

.changeset/rotten-mails-join.md
src/utils/siwe/validateSiweMessage.test.ts
src/utils/siwe/validateSiweMessage.ts

`validateSiweMessage` would return true if `message.address` was invalid but no top-level `address` was passed

Harden address validation in validateSiweMessage

---

site/pages/docs/actions/wallet/sendCalls.mdx

PR #3615 added the method `formatRequestCapabilities` to ensure `paymasterService` matched the format as described in the official EIP at https://eips.ethereum.org/EIPS/eip-7677#paymasterservice-capability. The docs did not reflect this change so this PR updates them.
NOTE: Coinbase's paymaster does not honor the correct format of paymaster capabilities and still expects `url` to be the key directly under `paymasterService`. I found this topic trying to resolve the issue in my app which is still not resolved. There is an open ticket in Coinbase's discord and I've brought the issue up in Viem's discord as well. I'm not sure if other paymaster services are honoring this format or not. Further discussion and documentation of the errors I encountered are in #3615.

Update sendCalls docs to match eips

---

.changeset/odd-books-push.md
package.json
site/pages/docs/actions/wallet/sendCalls.mdx
src/actions/wallet/getCallsStatus.test.ts
src/actions/wallet/getCallsStatus.ts
src/actions/wallet/sendCalls.test.ts
src/actions/wallet/sendCalls.ts

Adds `experimental_fallback` property to `sendCalls` to indicate for Viem to fall back to executing the calls sequentially
via `eth_sendTransaction` if the wallet does not support EIP-5792.
The `experimental_fallback` property enables [this behavior](https://eips.ethereum.org/EIPS/eip-5792#specification) on the spec:
> Apps may begin using these first three methods immediately, falling back to eth_sendTransaction and eth_getTransactionReceipt when they are not available.

feat: fall back to `eth_sendTransaction` on `sendCalls`

---

.changeset/stale-kings-return.md
src/zksync/utils/getEip712Domain.test.ts
src/zksync/utils/getEip712Domain.ts

Changes default calldata in zksync from being a single zero byte to being empty.
Related to #3456

fix: fix zksync default calldata

---

.changeset/tricky-hairs-pretend.md
src/utils/abi/decodeEventLog.test.ts
src/utils/abi/decodeEventLog.ts

Hi!
Noticed that `decodedEventLog` is returning arguments in the wrong order for events with unnamed arguments where the indexed parameters are not placed at the start. 
Here is a reproduction
```typescript
import { parseAbi, decodeEventLog } from "viem/utils";
const event: {
eventName: "Transfer";
args: readonly [`0x${string}`, bigint, `0x${string}`]; // typed arguments
} = decodeEventLog({
abi: parseAbi(["event Transfer(address indexed, uint256, address indexed)"]), // valid sol
data: "0x0000000000000000000000000000000000000000000000000000000000000001",
topics: [
"0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
"0x000000000000000000000000a5cc3c03994db5b0d9a5eedd10cabab0813678ac",
"0x000000000000000000000000a5cc3c03994db5b0d9a5eedd10cabab0813678ac",
],
}); …
```

fix: `decodeEventLog` mixing order of parameters

---

pnpm-lock.yaml
src/constants/abis.ts

…ointer
Fixes a typo in the ERC721 ABI constant where tokenId was incorrectly spelled as tokeId.
Changes
Fix #3709  typo in src/constants/abis.ts line 1416
Changed tokeId to tokenId in the ERC721 ABI definition

fix: correct typo in erc721Abi from 'tokeId' to 'tokenId'

---

.changeset/seven-balloons-visit.md
src/chains/definitions/blast.ts

This PR adds the contract addresses to Blast to improve ability to interact with withdrawal functionality.
These contract addresses are pulled from https://docs.blast.io/building/contracts

ENH: Add Blast contracts for op-stack compatability

---

.changeset/plenty-donkeys-type.md
src/types/calls.ts

when passing args to `simulateBlocks` through `Array.map()`, `extraProperties` does not participate in infer.
#3743

Add `extraProperties` to infer the param types

---

.changeset/wild-brooms-teach.md
src/types/eip1193.ts

The documentation was incorrectly describing eth_call behaviour instead of eth_createAccessList.

fix: correct `eth_createAccessList` method documentation in eip1193 types

---

.changeset/nervous-jobs-kick.md
src/utils/ens/localBatchGatewayRequest.test.ts
src/utils/ens/localBatchGatewayRequest.ts

- allow recursion in local batch gateway to support nested batching

fix: Local Batch Gateway Recursion

---

.changeset/curly-glasses-fix.md
src/clients/transports/webSocket.test.ts
src/utils/rpc/socket.ts
src/utils/rpc/webSocket.test.ts

Fixes #3771
This PR fixes the issue where WebSocket subscriptions are lost after a reconnection and not automatically restored. When using the WebSocket transport with `reconnect: true`, subscriptions created via `watchBlockNumber`, `watchContractEvent`, etc. would silently stop working after the connection dropped and reconnected.

Replay subscriptions when reconnecting in websocket

---

.changeset/happy-ducks-destroy.md
.changeset/honest-rice-protect.md
site/pages/docs/clients/public.md
src/actions/public/call.ts
src/actions/public/estimateGas.ts
src/actions/public/getBalance.ts
src/actions/public/getBlock.ts
src/actions/public/simulateBlocks.ts
src/actions/public/waitForTransactionReceipt.ts
src/actions/public/watchBlocks.ts
src/chains/definitions/base.ts
src/chains/definitions/baseSepolia.ts
src/clients/createClient.test.ts
src/clients/createClient.ts
src/types/chain.ts

Brings back https://github.com/wevm/viem/commit/530f0f1693983c7de1676873f9f234033e5267e1 via a Client option (`client.experimental_blockTag`), and a `chain.experimental_preconfirmationTime` for chains that support preconfirmations (e.g. "Flashblocks").

feat: add `client.experimental_blockTag` + `chain.experimental_preconfirmationTime`

---

.changeset/famous-pans-act.md
src/chains/definitions/arbitrum.ts
src/chains/definitions/arbitrumSepolia.ts

Adds block time for Arbitrum - based on [docs](https://docs.arbitrum.io/how-arbitrum-works/timeboost/gentle-introduction#:~:text=It's%20important%20to%20note%20that,to%20100%20milliseconds%20if%20desired) and block times it is 250 ms.
Should we remove Arbitrum Goerli? It's deactivated since March 18th, 2024 - https://docs.arbitrum.io/build-decentralized-apps/public-chains#arbitrum-goerli.

Add block time for Arbitrum chain

---

.changeset/tall-peas-doubt.md
src/chains/index.ts

AstarZkEVM and AstarZkyoto have been deprecated for some time.
https://web.archive.org/web/20250118215916/https://forum.astar.network/t/astar-zkevm-sunsetting-migration-plan/7780
https://github.com/wevm/viem/pull/3829
Instead of a rebase I had to do git reset hard from main, and then cherry-pick the specific commits. 
@jxom

Remove deprecated astarzkevm and astarzkyoto

---

src/chains/definitions/mainnet.ts

Adds Ethereum mainnet block time (12s - https://ycharts.com/indicators/ethereum_average_block_time)

Add Ethereum mainnet block time

---

src/chains/definitions/story.ts
src/chains/definitions/storyAeneid.ts
src/chains/definitions/storyOdyssey.ts
src/chains/definitions/storyTestnet.ts

- Update explorer links for Story mainnet and Story Aeneid testnet
- Deprecate the old Story testnet and the unsupported Story testnet
Fixed based on requests from #3828

fix: update story explorer & deprecate old story testnets

---

.changeset/nine-comics-doubt.md
src/actions/wallet/sendCalls.ts

Add support for sendCalls fallback with magic.link
Improved version of https://github.com/wevm/viem/pull/3845
The full error from magic.link
```
InternalRpcError: An internal error was received.
Details: Magic RPC Error: [-32603] Feature toggled misconfigured
Version: viem@2.33.3
at delay.count.count (buildRequest.ts:170:25)
at async attemptRetry (withRetry.ts:44:22)Caused by: r: Magic RPC Error: [-32603] Feature toggled misconfigured
```
How I got the error.
```typescript
console.log(error);
```

Support magic.link with sendCalls fallback

---

.changeset/tasty-fireants-smoke.md
src/chains/definitions/eduChain.ts

Added Multicall3 contract details to EDU Chain mainnet configuration.
- Updated `src/chains/definitions/eduChain.ts` to include multicall3 contract configuration
- Added contract address: `0xcA11bde05977b3631167028862bE2a173976CA11`
- Added deployment block: `16410660`
- Contract deployed today on EDU Chain mainnet
- Uses standard Multicall3 address consistent with other chains
- Can be verified on [EDU Chain Explorer](https://educhain.blockscout.com/address/0xcA11bde05977b3631167028862bE2a173976CA11)
- Follows established pattern used by other chains in the repository
- Changeset created for proper versioning
Resolves the missing multicall3 functionality for EDU Chain users.

Add Multicall3 contract to EDU Chain mainnet

---

.changeset/fifty-coins-act.md
src/utils/rpc/http.test.ts
src/utils/rpc/http.ts

adds optional `fetchFn` parameter to http transport config to allow full interception/decorator/mocking of fetch
this is useful for a number of scenarios including:
- applying a decorator to node fetch for capturing metrics
- easier testing by passing a mock fetch instead of overwriting global fetch
- any scenario where the client needs to be able to process hooks before and after a fetch, while maintaining the same context. This can't be done with the current onRequest/onResponse as there is no way to link the two calls to the same request/response cycle

feat: add optional `fetchFn` override to http transport to allow full fetch interception

---

.changeset/kind-boxes-walk.md
src/actions/wallet/waitForCallsStatus.ts

We'd like to use a custom implementation of the `getCallsStatus` from the `client` within `waitForCallsStatus`.

fix: use getAction within waitForCallsStatus

---

.changeset/empty-ws-messages.md
src/utils/rpc/webSocket.test.ts
src/utils/rpc/webSocket.ts

I noticed that we are getting intermittent errors on some networks, specifically observed on Gnosis and Polygon when connecting to an Erigon client using a websocket transport (so I'm assuming this is specific to Erigon). This error happens in about 1% of requests sent - randomly.
After debugging, I realized the problem was that the server was sending an empty string as a message on the connection, which viem then attempts to parse into JSON and fails with `Unexpected end of JSON input`
The problem is that Viem attributes this failure to one of the requests and makes it fail.
I then tested whether ignoring the message makes the original request succeed, and it does.
So I wrote a test that reproduces the issue and then added handling to simply ignore empty messages or messages that just …

Fix handling of empty WebSocket messages
